apiVersion: apps/v1
kind: Deployment
metadata:
  name: zably-contracts
  namespace: zably-dev
  labels:
    app: zably-contracts
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zably-contracts
  template:
    metadata:
      labels:
        app: zably-contracts
        version: v1.0.0
    spec:
      serviceAccountName: zably-contracts
      containers:
      - name: contracts
        image: zably/contracts:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - configMapRef:
            name: zably-contracts-config
        - secretRef:
            name: zably-contracts-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - node
            - -e
            - "console.log('Health check passed'); process.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - node
            - -e
            - "console.log('Ready check passed'); process.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30