apiVersion: v1
kind: Secret
metadata:
  name: zably-contracts-secret
  namespace: zably-dev
  labels:
    app: zably-contracts
    version: v1.0.0
type: Opaque
data:
  # S2S Authentication (base64 encoded)
  S2S_CLIENT_ID: emFibHktY29udHJhY3Rz  # zably-contracts
  S2S_CLIENT_CERT: LS0tLS1CRUdJTi0tLS0t  # placeholder cert
  S2S_CLIENT_KEY: LS0tLS1CRUdJTi0tLS0t   # placeholder key
  S2S_CA_CERT: LS0tLS1CRUdJTi0tLS0t     # placeholder CA
  
  # Event Bus Credentials
  EVENT_BUS_USERNAME: emFibHk=           # zably
  EVENT_BUS_PASSWORD: cGFzc3dvcmQ=       # password