apiVersion: v1
kind: Service
metadata:
  name: zably-contracts
  namespace: zably-dev
  labels:
    app: zably-contracts
    version: v1.0.0
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: zably-contracts